# Generated by Django 6.0.5 on 2026-05-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
