# Generated by Django 6.0.5 on 2026-05-09 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0002_stockitem_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('items_sold', models.TextField(help_text='JSON format or text description of items')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transport_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Credit', 'Credit')], default='Pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Bank Transfer', 'Bank Transfer')], default='Cash', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('sold_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
    ]
