# Generated by Django 6.0.5 on 2026-05-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0005_suppliercredit_suppliercreditpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='tin_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
