# Generated by Django 6.0.5 on 2026-05-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0010_deposit_depositpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='wants_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
