# Generated by Django 6.0.3 on 2026-05-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0011_sale_wants_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='item_type',
            field=models.CharField(choices=[('Cement CEM II N', 'Cement CEM II N'), ('Cement CEM III N', 'Cement CEM III N'), ('Iron Sheets', 'Iron Sheets'), ('Iron Bars 10mm', 'Iron Bars 10mm'), ('Iron Bars 12mm', 'Iron Bars 12mm'), ('Iron Bars 16mm', 'Iron Bars 16mm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='category',
            field=models.CharField(choices=[('Cement', 'Cement'), ('Iron Bars', 'Iron Bars'), ('Iron Sheets', 'Iron Sheets'), ('Nails', 'Nails'), ('Wheelbarrows', 'Wheelbarrows'), ('Wire Mesh', 'Wire Mesh'), ('Barbed Wire', 'Barbed Wire')], max_length=40),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(choices=[('Pieces', 'Pieces'), ('Bags', 'Bags'), ('Sheets', 'Sheets'), ('Packs', 'Packs'), ('Rolls', 'Rolls'), ('Bundles', 'Bundles'), ('Kilograms', 'Kilograms'), ('Metres', 'Metres')], default='Pieces', max_length=20),
        ),
    ]
