# Generated by Django 6.0.5 on 2026-05-20 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0012_alter_deposit_item_type_alter_stockitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nyondoapp.stockitem'),
        ),
    ]
