# Generated by Django 6.0.5 on 2026-05-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0014_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Discontinued', 'Discontinued'), ('Seasonal', 'Seasonal')], default='Active', max_length=20),
        ),
    ]
