# Generated by Django 6.0.5 on 2026-05-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0015_stockitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='tin_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='TIN Number'),
        ),
    ]
